development:
  adapter: postgresql
  encoding: unicode
  database: ceds3225_development
  pool: 5
  username: davidortizfrau
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: ceds3225_test
  pool: 5
  username: davidortizfrau
  password:
